blank_lines_lower_bound = 1
max_width = 80
wrap_comments = true
comment_width = 50
format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Crate"
use_field_init_shorthand = true
fn_args_layout = "Vertical"
normalize_comments = true
group_imports = "StdExternalCrate"
