[workspace]
members = [
  "biorite_server",
  "biorite_client",
  "biorite_shared",
  "biorite_generator",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "thin"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3